[package]
name = "d-r-o-n-e_drone"
version = "0.1.0"
edition = "2021"

[dependencies]
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", rev="89d4c9dfebb05be246459b03d81b61064d0a15b2" }
crossbeam = "0.8.4"
rand = "0.8"
log = "0.4.22"
colored = "2.1.0"
